### ISSUE TITLE
Steps don't work on all .ans files

### ISSUE THREAD

**Issue by poetaman** [PhMajerus/ANSI-art#2]
Hi @PhMajerus,

Thanks for sharing this project and your notes on how to translate to UTF-8 ANSI. There seems to be something missing, it does not work on all ANSI files. Check the sample ANSI art at link below, and its PNG attached here. I also added you to another GitHub thread, but not sure if adding someone while doing a comment edit notifies them. Anyway, having it echoed here should also be useful for others who are facing similar problem trying to make ANSI art work on Unix terminals.

Link: https://github.com/blocktronics/artpacks/blob/master/Blockfury/LU-Holiday.ans

Png:
![LU-Holiday](https://user-images.githubusercontent.com/71736629/198755870-c735ec6b-2dfc-489f-b3e6-47e234c64376.png)

As a sidenote, I recently published a project that is a ASCII/ANSI art viewer in terminal as well as a clock/timer. There is not much ANSI art there as I have not found a technique that always works to make ANSI look clean on Unix terminals.

1) Homepage: https://github.com/poetaman/arttime
2) Screenshots: https://github.com/poetaman/arttime#screenshots
3) Installation: https://github.com/poetaman/arttime#installation
4) Release notes for latest version (1.9.2): https://github.com/poetaman/arttime/releases/tag/v1.9.2
5) Your supermario ANSI art just made it to arttime's collection (hope that's fine): https://github.com/poetaman/arttime/commit/b6a8a3a6be36659044078d788069152525e5664c#commitcomment-88245924

Thanks!

**Comment by PhMajerus** [comment]
@poetaman 
You'll need more work than just those commands to convert ANSIs designed for the hardware console.

There are basically three main categories of ANSIs :
- Legacy ones designed for hardware terminal (aka console), text video adapters (MDA/CGA mostly), or firmware software text modes (VGA and later), those were a single 8-bit codepage (usually CP 437) and always 80 columns or 160 columns (uncommon, and usually distributed as .bin, not .ans).
- MS-DOS and Windows 9x with support for a single 8-bit codepage (usually CP 437, but can be 850, 932, ...), and with an arbitrary number of columns (which can even be resized without being cleared on Windows).
- Modern Unix and Windows NT, with support for full Unicode and arbitrary and resizable number of columns.

The .ans files in my repository are designed for modern terminals, not a hardware or firmware console, they work with the Windows `type` command in the Windows console or terminal, but do not assume a specific number of columns.
The `| iconv -f CP437 | sed 'H;$!d;x;s/\x1A.*$//'` commands only convert to codepage from 437 to UTF-8 and trim anything following the CP/M and MS-DOS text file terminator, as it is sometimes used to include extra information that is not displayed by the CMD `type` command.

![image](https://user-images.githubusercontent.com/25664275/198824418-092bcdac-845b-4991-9cb7-9d500dee84a4.png)

You'll need to understand the history of the hardware terminal and software console to write a complete conversion function for legacy ANSIs.
In the old days of hardware terminals and the IBM PC 5150, the electronics managing the display would have a fixed number of columns and lines, and a set of characters in ROM. The characters were originally 7-bit but quickly got extended to 8-bit (256 characters, some of which were also handled as special in-band control codes).
You have to understand there were no bitmap mode with software rendering those characters, it was a hardware text mode, with a ROM chip containing a fixed set of characters, a RAM chip containing a screen buffer (instead of a frame buffer), and some simple circuitry looping through the screen buffer, picking the required on/off signal from the character ROM for the corresponding position within the current character being rendered.

Outputting text was just a matter of updating the screen buffer, copying the bytes received into the cursor position and incrementing that position. If we were already at column 80 it would wrap to the first column of the next line, this wouldn't even require any specific handling as the buffer was linear in RAM anyway. It would also shift the whole buffer by 80 if it was the last line of the buffer to make it scroll by one line (discarding the top row).
And this is where it looks the same as modern terminals but is in fact slightly different and enough to break your ANSI arts.
On legacy consoles, if you output a line containing 80 characters, your cursor is automatically at the first column of the next line, because that is the next position in a fixed-width screen buffer. If you were to process a CR/LF at this point, the circuit would simply jump to the next multiple of 80 to get to the beginning of the next line, resulting in an empty line.
This means legacy-style ANSIs will have CR/LF at the end of a line **only** if that line is narrower than 80 characters, as having it as the 80th character would not make the next line appear below, but create an unwanted separating line.
In modern terminals, a CR/LF after the last column will typically not introduce an empty line, the terminal remembers that it is in the first column of the next line because the previous character reached the right border and the CR/LF will no change the cursor position in that special scenario.
On Windows, since the original WinNT console was designed to emulate the hardware console, not a terminal, this behavior can be changed using the ENABLE_WRAP_AT_EOL_OUTPUT SetConsoleMode flag.

What does this all mean for you? Well it means those legacy-style ANSIs will only display properly if you simulate that behavior of an 80 columns buffer. This can be done by outputting it within a software-defined text window that is 80 columns (if you resize your terminal to 80 columns you'll see it usually renders fine), or by processing the file to insert the missing CR/LF to be independent of the width of the terminal. Processing the file to add missing CR/LF would be the cleanest solution as then your terminal can properly resize the content when its window is resized.
This can however be tricky, as the file is not simply text. You'll have to handle VT escape sequences like a terminal would to find out when you reach that end of a line to insert the missing CR/LF.
Fortunately, most ANSIs only use VT for colors and reverse commands, not for cursors movements. So a temporary implementation could just count the characters ignoring everything between `ESC[` and `m`. To handle all files, you'll have to improve on that solution and write a full VT parser that behaves like the original text mode. Fortunately you can probably expect it to be limited to what MS-DOS ANSI.SYS supported.

This isn't the end, I'll follow up with details about the SUB (\x1A) character, but while there is history to understand why that character is so special, the fix is simple, if you encounter a SUB character, stop processing the file.
Also upcoming: background assumptions, legacy RGBI palette, ...

**Comment by poetaman** [comment]
@PhMajerus Thanks, I just had my first success in hand-editing that file. I really appreciate your sharing such historical insight into ANSI, will get back tomorrow (its a little late here).

Here's the link to the result, and command to run it:

https://github.com/poetaman/arttime/commit/153cd08e2c21903efd0ed90a9d0b54388823e274#commitcomment-88263554
